### PR TITLE
chore: repository governance

### PR DESCRIPTION
**Pull request by mbilalamjad**
## Repository governance update

This PR was automatically created by the AVM Team hive-mind using the [grept](https://github.com/Azure/grept) governance tool.

We have detected that some files need updating to meet the AVM governance standards.
Please review and merge with alacrity.

Grept config source: `git::https://github.com/Azure/Azure-Verified-Modules-Grept.git//terraform`

Thanks! The AVM team :heart:

### CODE REVIEW

**Comment by cshea-msft** [comment]
@mbilalamjad @matt-FFFFFF How should I fix the linting/avmfix error? I tried running that docker command but still fails

**Comment by mbilalamjad** [comment]
> @mbilalamjad @matt-FFFFFF How should I fix the linting/avmfix error? I tried running that docker command but still fails

Did you try running avm.bat pre-commit, does it make any updates to the repo files which you need to push ?

**Comment by cshea-msft** [comment]
> > @mbilalamjad @matt-FFFFFF How should I fix the linting/avmfix error? I tried running that docker command but still fails
> 
> Did you try running avm.bat pre-commit, does it make any updates to the repo files which you need to push ?

I was able to fix it. i ran the ./avm pre-commit again. Not sure why it didn't work before but it works now. Thanks!

**Comment by cshea-msft** [comment]
closing fixed from another PR

**Pull request closed without merging**
